config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  # root 'static_pages#home' #Рут - страничка авторизации.
  root 'sessions#new'
  #Sessions Block
  # match '/signin',  to: 'sessions#new',         via:    'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  #Static Pages Block
  match '/home',    to: 'static_pages#home',    via:    'get'
  match '/help',    to: 'static_pages#help',    via:    'get'
  ######
  match '/readapp', to: 'static_pages#readapp', via:    'get'
  match '/formapp', to: 'static_pages#formapp', via:    'get'
  match '/call',    to: 'static_pages#call',    via:    'get'
  #Users Block
  match '/edit',    to: 'users#edit',           via:    'get'
  match '/signup',  to: 'users#new',            via:    'get'
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  before_save {self.email = email.downcase}
  before_create :create_remember_token


  validates :name,    presence: true, length: { maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,   presence: true,
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, length: { minimum: 6 }

  def should_generate_new_friendly_id?
    new_record?
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  include SessionsHelper
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid user Information"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def readapp
  end

  def formapp
  end

  def call
  end

  def exit
  end

  def office
  end

  def signin
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.friendly.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Пользователь успешно создан!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.friendly.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Профиль успешно изменен"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Пожалуйста выполните вход"
    end
  end

  def correct_user
    @user = User.friendly.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Tofu"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
      remember_token = User.new_remember_token
      cookies.permanent[:remember_token] = remember_token
      user.update_attribute(:remember_token, User.encrypt(remember_token))
      self.current_user = user
    end

    def sign_out
      current_user.update_attribute(:remember_token,
                                    User.encrypt(User.new_remember_token))
      cookies.delete(:remember_token)
      self.current_user = nil
    end

    def signed_in?
      !current_user.nil?
    end

    def current_user=(user)
      @current_user = user
    end

    def current_user
      remember_token = User.encrypt(cookies[:remember_token])
      @current_user ||= User.find_by(remember_token: remember_token)
    end

    def current_user?(user)
      user == current_user
    end

    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      session.delete(:return_to)
    end

    def store_location
      session[:return_to] = request.url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_adminappview.html.erb
<div class="accord-container">
  <div class="accordion">
    <input type="radio" id="1" name="accordion"/>
    <label for="1" class="accordion-section">
      <h3 class="accordion-header">Заявки Бухгалтерии</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="2" name="accordion"/>
    <label for="2" class="accordion-section">
      <h3 class="accordion-header">Заявки Отдела Кадров</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="3" name="accordion"/>
    <label for="3" class="accordion-section">
      <h3 class="accordion-header">Заявки Применой</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="4" name="accordion"/>
    <label for="4" class="accordion-section">
      <h3 class="accordion-header">Заявки Музыкальной Библиотеки (Перерва)</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="5" name="accordion"/>
    <label for="5" class="accordion-section">
      <h3 class="accordion-header">Заявки Ателье</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="6" name="accordion"/>
    <label for="6" class="accordion-section">
      <h3 class="accordion-header">Заявки Черноног Анны</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="7" name="accordion"/>
    <label for="7" class="accordion-section">
      <h3 class="accordion-header">Заявки PR-Отдела</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="8" name="accordion"/>
    <label for="8" class="accordion-section">
      <h3 class="accordion-header">Заявки Радио Орфей</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="9" name="accordion"/>
    <label for="9" class="accordion-section">
      <h3 class="accordion-header">Заявки Первого Этажа</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="10" name="accordion"/>
    <label for="10" class="accordion-section">
      <h3 class="accordion-header">Заявки Тех. Отдела</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="11" name="accordion"/>
    <label for="11" class="accordion-section">
      <h3 class="accordion-header">Заявки Чебоксарова Святослава</h3>
      <p>ололоо трололо</p>
    </label>
    <input type="radio" id="12" name="accordion"/>
    <label for="12" class="accordion-section">
      <h3 class="accordion-header">Заявки Бабичева</h3>
      <p>ололоо трололо</p>
    </label>
  </div>
</div>

<!--  Список заказчиков:
бухгалтерия Чукова
отдел кадров Кондаурова

приемная Савина
музыкальное хранилище Воробьева
библиотека
ателье Фурманюк
агафонников Черноног
пиар отдел Семененко
орфей Кулешова
первый этаж хз кто
айти отдел Банников
Чебоксаров Святослав
Бабичев
-->

app/views/layouts/_footer.html.erb
<div class="greyLine">
</div>
<div class="footer">
  &#169; Tofu
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TOFUONERY", '#', id: "logo" %>
      <div class="kancel_logo">
        <%= image_tag("kancel_logo.jpg", alt: "Stationery")  %>
      </div>
      <nav>

        <ul class="nav pull-right">
            <% if signed_in? %>
          <li><%=link_to "Личный Кабинет", home_path %></li>
          <li><%=link_to "Помощь", help_path %></li>
          <li><%=link_to "Выйти", signout_path, method: "delete" %></li>
          <% else %>
          <li><%= link_to "Войти", root_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_navbackhome.html.erb
  <div class="linkbox">
  <%= link_to "Вернуться",               home_path,
  class: "btn btn-large btn-success btn-block" %>
  </div>

app/views/layouts/_signiner.html.erb
<% provide(:title, 'Welcome') %>
<div class="WelcomeMessage">
  <h1>Добро пожаловать в Tofuonery!</h1>
  <h2>Пожалуйста, введите свои учетные данные и нажмите кнопку "Войти".</h2>
</div>
<div class="row">
  <div class="span5 offset3">
    <%= form_for(:session, url: sessions_path) do |f| %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Войти", class: "btn btn-large btn-success" %>
    <% end %>
  </div>
</div>

app/views/layouts/_userappview.html.erb
КОНТЕНТ В РАЗРАБОТКЕ

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      <% if signed_in? %>
      <%= yield %>
      <% else %>
      <%= render 'layouts/signiner'%>
      <% end %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/call.html.erb
<% provide(:title, 'Feedback') %>
<div class="WelcomeMessage">
  <h1>РГМЦ Канцелярия v 0.1</h1>
</div>
<div class="center hero-unit">
<%= render 'layouts/navbackhome' %>
</div>

app/views/static_pages/formapp.html.erb
<% provide(:title, 'New Application') %>
<div class="WelcomeMessage">
  <h1>РГМЦ Канцелярия v 0.1</h1>
</div>
<div class="center hero-unit">
<%= render 'layouts/navbackhome' %>
</div>

app/views/static_pages/help.html.erb
  <% provide(:title, 'Help') %>
  <div class="WelcomeMessage">
    <h1>Помощь</h1>
  </div>
  <div class="center hero-unit">
    <div class="linkbox">
      <%= link_to "Как работать с приложением",  'howorks_path',
      class: "btn btn-large btn-info btn-block" %>
    </div>
    <div class="linkbox">
    <%= link_to "Сообщить об ошибке",             'sendbug_path',
    class: "btn btn-large btn-danger btn-block" %>
    </div>
  </div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Stationery') %>
<div class="WelcomeMessage">
  <h1>РГМЦ Канцелярия v 0.1</h1>
</div>
<div class="center hero-unit">
  <div class="linkbox">
    <%= link_to "Сформировать Новую Заявку",  formapp_path,
    class: "btn btn-large btn-info btn-block" %>
  </div>
  <div class="linkbox">
  <%= link_to "Просмотреть Заявки",           readapp_path,
  class: "btn btn-large btn-info btn-block" %>
  </div>
  <div class="linkbox">
  <%= link_to "Редактрировать профиль",       edit_user_path(current_user),
  class: "btn btn-large btn-success btn-block" %>
  </div>
  <div class="linkbox">
  <%= link_to "Обратная Связь",               call_path,
  class: "btn btn-large btn-success btn-block" %>
  </div>
</div>

app/views/static_pages/readapp.html.erb
<% provide(:title, 'Read Application') %>
<div class="WelcomeMessage">
  <h1>РГМЦ Канцелярия v 0.1</h1>
</div>
<% if current_user.admin? %>
 <%= render 'layouts/adminappview' %>
<% else %>
<%= render 'layouts/userappview' %>
<% end %>
<div class="center hero-unit">
<%= render 'layouts/navbackhome' %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Редактирование Профиля</h1>

<div class="row">
  <div class="span5 offset4">
    <div class="gravatar">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">change</a>
    </div>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "Логин" %>
      <%= f.text_field :name %>

      <%= f.label :email, "@mail" %>
      <%= f.text_field :email %>

      <%= f.label :password, "Пароль" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Подтверждение Пароля" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Сохранить изменения", class: "btn btn-large btn-success" %>
    <% end %>
  </div>
  <%= render 'layouts/navbackhome' %>
</div>

app/views/users/index.hmtl.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= provide(:title, 'New User') %>
<h1>Создание Нового Пользователя</h1>
<% if current_user.admin? %>
<div class="row">
  <div class="span5 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name  %>

    <%= f.label :email  %>
    <%= f.text_field :email  %>

    <%= f.label :password  %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation  %>

    <%= f.submit "Создать нового пользователя", class: "btn btn-large btn-danger"  %>
    <% end %>
  </div>
</div>
<% else %>
<div class="signup-error">
  <%= image_tag("hey-you.jpg", alt: "Hey You!", size: "250x168")  %>
  <br> <br>
  ВАМ НЕ ХВАТАЕТ ПРАВ ДЛЯ СОЗДАНИЯ НОВОГО ПОЛЬЗОВАТЕЛЯ, <br><br>
  ПОЖАЛУЙСТА, ОБРАТИТЕСЬ К АДМИНИСТРАТОРУ САЙТА ИЛИ <br><br>
  ПРЕКРАТИТЕ ПОПЫТКИ СОЗДАНИЯ НОВОГО ПОЛЬЗОВАТЕЛЯ <br><br>
</div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>